version: '3'

services:
  ark-eth-channel:
    image: rokson/aces-ark-ethereum-channel-service:latest
    command: mvn spring-boot:run
    environment:
      EVENT_CALLBACK_URL: "http://ark-eth-channel:9190/arkEvents"
      APP_PORT: 9190
      SERVICE_ETH_ADDRESS: "<your-eth-address-hodling-bags-of-eth>"
      SERVICE_FLAT_FEE: 0
      SERVICE_PERCENT_FEE: 1
      ETH_RPC_URL: "http://<eth-rpc>:8545"
      ARK_MIN_CONFIRMATIONS: 5
      ARK_LISTENER_URL: "http://listener-ark:9091"
    expose:
      - "9190"
    ports:
      - "9190:9190"
    volumes:
      - ark-eth-channel:/app

  listener-ark:
    image: rokson/aces-listener-ark
    command: mvn spring-boot:run
    environment:
      APP_PORT: 9091
      ARK_NETWORK: "devnet"
      SERVICE_ARK_NETWORK: "devnet"
      SERVICE_ARK_ADDRESS: "<your-dark-address-where-you-want-to-received-fees>"
      SERVICE_MIN_ARK_STAKE: "0"
      SERVICE_MIN_ARK_FEE: "1"
      SERVICE_REQUIRE_AUTH: 0
    expose:
      - "9091"
    ports:
      - "9091:9091"
    volumes:
      - listener-ark:/app

volumes:
  listener-ark:
  ark-eth-channel:
